### ISSUE TITLE
Authentication to selfhosted jira v8.20.11 fails

### ISSUE THREAD

**Issue by Jasper-Ben** [preslavmihaylov/todocheck#196]
Used config:

```yaml
origin: <jira_url>
issue_tracker: JIRA
auth:
  type: apitoken
  options:
    username: <username>
```

Auth token is parsed via environment variable:

```bash
TODOCHECK_AUTH_TOKEN=MY_TOKEN todocheck -verbose
```

Todo comment:

```
    # TODO RDPHOEN-1359: Unfreeze meta-openembedded after patch apply on cryptsetup has been fixed.
```

Error:

```
couldn't check todo line: couldn't fetch task status: bad status code upon fetching task: 403
```

User is definitely allowed access to the said issue. Am I doing something wrong or is Jira integration currently broken? Can someone confirm?
